### ISSUE TITLE
We need a Readme

### ISSUE THREAD

**Issue by ZhiquanW** [Arking1995/UrbanBrain#1]

**Comment by Arking1995** [comment]
This issue violates the community regulation. We give the user a poem:

ZhiquanW发顶刊TVCG，
自称高质量，众所称。
却见无脑稿，刷屏量，
资讯浮夸，大众狂。

慨叹现今传媒界，
诚信离我们何其远。
看着各种神奇妙药，
只问谁能接受真相问。

**Comment by ZhiquanW** [comment]
秋来何佬赏菊花，喷射器喷出美妙芬芳。
细雨洒落花丛中，佳景令人陶醉沉迷。
谁知此花来有毒，误入人眼害无穷。
何佬当意及此时，喷射器已难收回。
